
name: ci
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      -  name: validate the code
         uses: actions/checkout@v4
      -  name: set up python
         uses: actions/setup-python@v5
         with:
          python-version: '3.12'
      -  name: install reqs
         run: pip install -r requirements.txt
      -  name: run the test
         run: pytest
  docker:
    runs-on: ubuntu-latest
    permissions:
     packages: write
     contents: read
    needs: test
    steps:
      -  name: checking out
         uses: actions/checkout@v4
      -  name: loging in to GHCR
         uses: docker/login-action@v3
         with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -  name: build and push the Docker image
         uses: docker/build-push-action@v7
         with:
          push: true
          context: .
          tags: ghcr.io/a-ghanima/cloud-native-devops-platform:latest
